Issue 7 user sign in
vkahlon/final-project pull request #15
Opened 2022-03-04 23:40 UTC by vkahlon

Desktop Demo: Preventing mischief, user will get redirected back to the sign-in page if they try to access any feature. New Navbar, from Desktop perspective if the user is not signed on.
![Desktop Troll toll 1](https://user-images.githubusercontent.com/47346471/156855979-743d95f1-7e02-459e-b9ce-a41465883582.gif)

Mobile Sign-in Demo: Also provide a scenario if the login is invalid.

![mobile sign-in](https://user-images.githubusercontent.com/47346471/156856096-fd16ac40-f784-4414-8926-4cbf03ad1cca.gif)

Desktop Sign-in Demo: If the user just wants to browse, they select the guest option.

https://user-images.githubusercontent.com/47346471/156856197-448fcf9f-55b7-4b99-b1ab-dba937550dcf.mp4

Desktop Exploration of the App: Meals, exercises, and daily calorie correlate to Guest User
![Site has functionality Desktop](https://user-images.githubusercontent.com/47346471/156856222-cb42735c-0aa2-49d0-aa2f-e2bd9be8a347.gif)

Mobile View of Exploration of the App: Get to see user: Guy Fieri's meals, exercises and his daily calories

![Mobile Demo User Walkthrough](https://user-images.githubusercontent.com/47346471/156856312-2ec33021-666e-4e79-8fc8-5b8791fc67c1.gif)

Postgress images:
<img width="250" alt="users" src="https://user-images.githubusercontent.com/47346471/156856347-087af3a3-fe5f-4c47-9d3f-587872cae8e4.png">
<img width="759" alt="meal table" src="https://user-images.githubusercontent.com/47346471/156856348-57ba16e8-0d71-456d-8b3f-5f8d9f754489.png">
<img width="810" alt="exerciseId" src="https://user-images.githubusercontent.com/47346471/156856349-35f16dad-ff0d-43ba-9f12-b4e236d6a33a.png">

2022-03-04 23:50 UTC, thebearingedge requested changes

2022-03-04 23:50 UTC, thebearingedge commented on client/components/edit-form.jsx
> +    fetch(`/api/calorie/edit-${action}/${id}/${this.props.userId}`, req)
Instead of using a user id in the url path, you should send the token in the request headers and then use the id from the token payload, similar to how api-authorization is set up.

2022-03-05 23:52 UTC, vkahlon commented
Ensuring Functionality.

![Demo Feature 7](https://user-images.githubusercontent.com/47346471/156903527-e15be13b-24c9-4434-a106-9f731ef66d37.gif)

2022-03-06 00:05 UTC, thebearingedge approved these changes

2022-03-06 00:26 UTC, merged